/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author JULIO
 */
public class VentanaDespadida2 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaDespadida2
     */
    public VentanaDespadida2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPpregunta = new javax.swing.JPanel();
        jLPregunta2 = new javax.swing.JLabel();
        BSi = new javax.swing.JButton();
        No = new javax.swing.JButton();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPpregunta.setBackground(new java.awt.Color(102, 255, 255));
        jPpregunta.setForeground(new java.awt.Color(102, 255, 255));

        jLPregunta2.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        jLPregunta2.setText("¿ DESEA REGISTRAR NUEVAMENTE ?");

        javax.swing.GroupLayout jPpreguntaLayout = new javax.swing.GroupLayout(jPpregunta);
        jPpregunta.setLayout(jPpreguntaLayout);
        jPpreguntaLayout.setHorizontalGroup(
            jPpreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpreguntaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLPregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPpreguntaLayout.setVerticalGroup(
            jPpreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPpreguntaLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLPregunta2)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPpregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 550, 70));

        BSi.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        BSi.setText("SI");
        BSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSiActionPerformed(evt);
            }
        });
        getContentPane().add(BSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        No.setFont(new java.awt.Font("Orbitron", 1, 24)); // NOI18N
        No.setText("NO");
        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });
        getContentPane().add(No, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono1.jpg"))); // NOI18N
        jLFondo.setText("    ");
        getContentPane().add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSiActionPerformed
       
        VentanaRegistroDestinatario H =new VentanaRegistroDestinatario();
            H.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_BSiActionPerformed

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
         System.exit(0);
    }//GEN-LAST:event_NoActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSi;
    private javax.swing.JButton No;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLPregunta2;
    private javax.swing.JPanel jPpregunta;
    // End of variables declaration//GEN-END:variables
}
