/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.table.DefaultTableModel;
import java.io.DataOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JULIO
 */
public class VentanaRegistroPaquete extends javax.swing.JFrame {
    
    DefaultTableModel HMP =new DefaultTableModel();
    /**
     * Creates new form VentanaRegistroDestinatario
     */
    public VentanaRegistroPaquete() {
        initComponents();
        this.setLocationRelativeTo(null);
                
        TablaDatosDelPaquete.setModel(HMP);
        HMP.addColumn("Tipo");
        HMP.addColumn("Alto");
        HMP.addColumn("Ancho");
        HMP.addColumn("Largo");
        HMP.addColumn("Peso (kg)");
        HMP.addColumn("Descripcion");
        HMP.addColumn("Valor Declarado");
        HMP.addColumn("Fecha De Entrega");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPDatosDelPaquete = new javax.swing.JPanel();
        jLTipo = new javax.swing.JLabel();
        jLAlto = new javax.swing.JLabel();
        jLAncho = new javax.swing.JLabel();
        jLLargo = new javax.swing.JLabel();
        jLPesokg = new javax.swing.JLabel();
        jLDescripcion = new javax.swing.JLabel();
        jLValorDeclarado = new javax.swing.JLabel();
        jTextFieldTipo = new javax.swing.JTextField();
        jTextFieldAlto = new javax.swing.JTextField();
        jTextFieldAncho = new javax.swing.JTextField();
        jTextFieldLargo = new javax.swing.JTextField();
        jLDatosDelPaquete = new javax.swing.JLabel();
        jTPesokg = new javax.swing.JTextField();
        jTDescripcion = new javax.swing.JTextField();
        jTValorDeclarado = new javax.swing.JTextField();
        jLFechaLimiteEntrega = new javax.swing.JLabel();
        jTextFieldFechaDeEntrega = new javax.swing.JTextField();
        jPTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatosDelPaquete = new javax.swing.JTable();
        jLTitulo = new javax.swing.JLabel();
        jBSiguiente = new javax.swing.JButton();
        jLFormatoDePaqueteria = new javax.swing.JLabel();
        jBGuardar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPDatosDelPaquete.setBackground(new java.awt.Color(204, 255, 255));
        jPDatosDelPaquete.setForeground(new java.awt.Color(204, 255, 255));

        jLTipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLTipo.setText("Tipo:");

        jLAlto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLAlto.setText("Alto:");

        jLAncho.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLAncho.setText("Ancho:");

        jLLargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLLargo.setText("Largo:");

        jLPesokg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLPesokg.setText("Peso (kg):");

        jLDescripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLDescripcion.setText("Descrpcion:");

        jLValorDeclarado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLValorDeclarado.setText("Valor Declarado:");

        jTextFieldLargo.setText(" ");

        jLDatosDelPaquete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLDatosDelPaquete.setText("DATOS DEL PAQUETE");

        jTPesokg.setText(" ");

        jTDescripcion.setText(" ");

        jTValorDeclarado.setText("  ");

        jLFechaLimiteEntrega.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLFechaLimiteEntrega.setText("Fecha de entrega");

        jTextFieldFechaDeEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaDeEntregaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPDatosDelPaqueteLayout = new javax.swing.GroupLayout(jPDatosDelPaquete);
        jPDatosDelPaquete.setLayout(jPDatosDelPaqueteLayout);
        jPDatosDelPaqueteLayout.setHorizontalGroup(
            jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosDelPaqueteLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLDatosDelPaquete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDatosDelPaqueteLayout.createSequentialGroup()
                .addGroup(jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPDatosDelPaqueteLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLFechaLimiteEntrega)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFechaDeEntrega))
                    .addGroup(jPDatosDelPaqueteLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLTipo)
                                    .addComponent(jLAlto))
                                .addGroup(jPDatosDelPaqueteLayout.createSequentialGroup()
                                    .addComponent(jLAncho)
                                    .addGap(2, 2, 2)))
                            .addComponent(jLLargo))
                        .addGap(19, 19, 19)
                        .addGroup(jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldTipo)
                            .addComponent(jTextFieldAlto)
                            .addComponent(jTextFieldAncho)
                            .addComponent(jTextFieldLargo, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLDescripcion)
                            .addComponent(jLPesokg)
                            .addComponent(jLValorDeclarado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTPesokg)
                            .addComponent(jTDescripcion)
                            .addComponent(jTValorDeclarado, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))))
                .addGap(67, 67, 67))
        );
        jPDatosDelPaqueteLayout.setVerticalGroup(
            jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosDelPaqueteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLDatosDelPaquete)
                .addGap(33, 33, 33)
                .addGroup(jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTipo)
                    .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPesokg)
                    .addComponent(jTPesokg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDatosDelPaqueteLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLAncho)))
                    .addGroup(jPDatosDelPaqueteLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLAlto)
                            .addComponent(jTextFieldAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDescripcion)
                            .addComponent(jTDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLLargo)
                    .addComponent(jTextFieldLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLValorDeclarado)
                    .addComponent(jTValorDeclarado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPDatosDelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFechaLimiteEntrega)
                    .addComponent(jTextFieldFechaDeEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPDatosDelPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 540, 370));

        TablaDatosDelPaquete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaDatosDelPaquete);

        javax.swing.GroupLayout jPTablaLayout = new javax.swing.GroupLayout(jPTabla);
        jPTabla.setLayout(jPTablaLayout);
        jPTablaLayout.setHorizontalGroup(
            jPTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
        jPTablaLayout.setVerticalGroup(
            jPTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        getContentPane().add(jPTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 580, 280));

        jLTitulo.setFont(new java.awt.Font("Orbitron", 1, 64)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo.setText("DELIVERY - UPAR");
        getContentPane().add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 680, -1));

        jBSiguiente.setBackground(new java.awt.Color(102, 255, 255));
        jBSiguiente.setFont(new java.awt.Font("Orbitron", 1, 18)); // NOI18N
        jBSiguiente.setText("SIGUIENTE");
        jBSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jBSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 640, -1, 30));

        jLFormatoDePaqueteria.setFont(new java.awt.Font("Orbitron", 1, 36)); // NOI18N
        jLFormatoDePaqueteria.setForeground(new java.awt.Color(102, 255, 255));
        jLFormatoDePaqueteria.setText("Formato de paqueteria");
        getContentPane().add(jLFormatoDePaqueteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        jBGuardar.setBackground(new java.awt.Color(102, 255, 255));
        jBGuardar.setFont(new java.awt.Font("Orbitron", 1, 18)); // NOI18N
        jBGuardar.setText("GUARDAR");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, -1, 30));

        jBCancelar.setBackground(new java.awt.Color(102, 255, 255));
        jBCancelar.setFont(new java.awt.Font("Orbitron", 1, 18)); // NOI18N
        jBCancelar.setText("CANCELAR");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, -1, 30));

        jBEliminar.setBackground(new java.awt.Color(102, 255, 255));
        jBEliminar.setFont(new java.awt.Font("Orbitron", 1, 18)); // NOI18N
        jBEliminar.setText("ELIMINAR");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 650, -1, 30));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo456.jpg"))); // NOI18N
        jLFondo.setText("jLabel1");
        getContentPane().add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1373, 758));

        pack();
    }// </editor-fold>//GEN-END:initComponents
void ArchivarDatos() throws FileNotFoundException{
     FileOutputStream hp=new FileOutputStream("RegistroDeliveryUparPaquetes.txt",true);
     DataOutputStream ph=new DataOutputStream(hp);
 
     try {
        String Tipo,Largo,Ancho,Alto,Pesokg,Descripcion,ValorDeclarado,FechaLimite;


        Tipo=jTextFieldTipo.getText();
        Alto=jTextFieldAlto.getText();
        Largo=jTextFieldLargo.getText();
        Ancho=jTextFieldAncho.getText();
        Pesokg=jTPesokg.getText();
        Descripcion=jTDescripcion.getText();
        ValorDeclarado=jTValorDeclarado.getText();
        FechaLimite=jTextFieldFechaDeEntrega.getText();
        


        ph.writeUTF(Tipo);
        ph.writeUTF(Alto);
        ph.writeUTF(Largo);
        ph.writeUTF(Ancho);
        ph.writeUTF(Pesokg);
        ph.writeUTF(Descripcion);
        ph.writeUTF(ValorDeclarado);
        ph.writeUTF(FechaLimite);


        } catch (Exception k) {
        }
}    
    
    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
      
        try{ ArchivarDatos();    
            } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaRegistroRemitente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        HMP.addRow(new Object[]{
            jTextFieldTipo.getText(), jTextFieldAlto.getText(),jTextFieldLargo.getText(),jTextFieldAncho.getText(),jTPesokg.getText(),
            jTDescripcion.getText(),jTValorDeclarado.getText(), jTextFieldFechaDeEntrega.getText()
        });

        

        jTextFieldTipo.setText("");
        jTextFieldAlto.setText("");
        jTextFieldLargo.setText("");
        jTextFieldAncho.setText("");
        jTPesokg.setText("");
        jTDescripcion.setText("");
        jTValorDeclarado.setText("");
        jTextFieldFechaDeEntrega.setText("");
      
                
        
        
        
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTextFieldFechaDeEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaDeEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaDeEntregaActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
      
        jTextFieldTipo.setText("");
        jTextFieldAlto.setText("");
        jTextFieldLargo.setText("");
        jTextFieldAncho.setText("");
        jTPesokg.setText("");
        jTDescripcion.setText("");
        jTValorDeclarado.setText("");
        jTextFieldFechaDeEntrega.setText("");
       
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        int fila = TablaDatosDelPaquete.getSelectedRow ();
        if (fila>=0){
            HMP.removeRow(fila);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccionar FIla, Por favor ");
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSiguienteActionPerformed
            
        VentanaDespadida2 H =new VentanaDespadida2();
            H.setVisible(true);
            this.setVisible(false);

    }//GEN-LAST:event_jBSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatosDelPaquete;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBSiguiente;
    private javax.swing.JLabel jLAlto;
    private javax.swing.JLabel jLAncho;
    private javax.swing.JLabel jLDatosDelPaquete;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLFechaLimiteEntrega;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLFormatoDePaqueteria;
    private javax.swing.JLabel jLLargo;
    private javax.swing.JLabel jLPesokg;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLValorDeclarado;
    private javax.swing.JPanel jPDatosDelPaquete;
    private javax.swing.JPanel jPTabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTDescripcion;
    private javax.swing.JTextField jTPesokg;
    private javax.swing.JTextField jTValorDeclarado;
    private javax.swing.JTextField jTextFieldAlto;
    private javax.swing.JTextField jTextFieldAncho;
    private javax.swing.JTextField jTextFieldFechaDeEntrega;
    private javax.swing.JTextField jTextFieldLargo;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
