/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.io.DataOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JULIO
 */
public class VentanaRegistroRemitente extends javax.swing.JFrame {
    
    DefaultTableModel HMP =new DefaultTableModel();
    /**
     * Creates new form VentanaRegistroRemitente
     */
    public VentanaRegistroRemitente() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        TablaDatosDelRemitente.setModel(HMP);
        HMP.addColumn("No Paquete");
        HMP.addColumn("Fecha Ingreso");
        HMP.addColumn("Nombres Completos");
        HMP.addColumn("Calle/Carrera");
        HMP.addColumn("No de Vivienda");
        HMP.addColumn("Pais");
        HMP.addColumn("Ciudad");
        HMP.addColumn("Telefono ");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPDatosRemitente = new javax.swing.JPanel();
        jLDatosDelRemitente = new javax.swing.JLabel();
        jLDireccion = new javax.swing.JLabel();
        jLPais = new javax.swing.JLabel();
        jTNombreCompleto = new javax.swing.JTextField();
        jTCalleCarrera = new javax.swing.JTextField();
        jTNoDeVivienda = new javax.swing.JTextField();
        jLCalleCarrera = new javax.swing.JLabel();
        jLNoDeVivienda = new javax.swing.JLabel();
        jTextFieldPais = new javax.swing.JTextField();
        jLNombreCompleto = new javax.swing.JLabel();
        jLCiudad = new javax.swing.JLabel();
        jLTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldCiudad = new javax.swing.JTextField();
        jPTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatosDelRemitente = new javax.swing.JTable();
        jBGuardar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLTitulo = new javax.swing.JLabel();
        jBEliminar = new javax.swing.JButton();
        jLFormatoDePaqueteria = new javax.swing.JLabel();
        jBSiguiente = new javax.swing.JButton();
        jLFondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPDatosRemitente.setBackground(new java.awt.Color(204, 255, 255));

        jLDatosDelRemitente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLDatosDelRemitente.setText("DATOS DEL REMITENTE");

        jLDireccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLDireccion.setText("Direccion:");

        jLPais.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLPais.setText("Pais:");

        jTCalleCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCalleCarreraActionPerformed(evt);
            }
        });

        jLCalleCarrera.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLCalleCarrera.setText("Calle/Carrera:");

        jLNoDeVivienda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLNoDeVivienda.setText("No De Vivienda:");

        jLNombreCompleto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLNombreCompleto.setText("NombreCompleto:");

        jLCiudad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLCiudad.setText("Ciudad:");

        jLTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLTelefono.setText("Telefono:");

        jTextFieldCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCiudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPDatosRemitenteLayout = new javax.swing.GroupLayout(jPDatosRemitente);
        jPDatosRemitente.setLayout(jPDatosRemitenteLayout);
        jPDatosRemitenteLayout.setHorizontalGroup(
            jPDatosRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosRemitenteLayout.createSequentialGroup()
                .addGroup(jPDatosRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDatosRemitenteLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPDatosRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPDatosRemitenteLayout.createSequentialGroup()
                                .addGroup(jPDatosRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPDatosRemitenteLayout.createSequentialGroup()
                                        .addComponent(jLDireccion)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPDatosRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLCalleCarrera)
                                            .addComponent(jLNoDeVivienda)))
                                    .addGroup(jPDatosRemitenteLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPDatosRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLTelefono)
                                            .addComponent(jLPais, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jTCalleCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPDatosRemitenteLayout.createSequentialGroup()
                                .addComponent(jLNombreCompleto)
                                .addGap(32, 32, 32)
                                .addComponent(jTNombreCompleto))))
                    .addGroup(jPDatosRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPDatosRemitenteLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTNoDeVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPDatosRemitenteLayout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addGroup(jPDatosRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPDatosRemitenteLayout.createSequentialGroup()
                                    .addComponent(jTextFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(jLCiudad)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 32, Short.MAX_VALUE))
            .addGroup(jPDatosRemitenteLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLDatosDelRemitente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPDatosRemitenteLayout.setVerticalGroup(
            jPDatosRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosRemitenteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLDatosDelRemitente)
                .addGap(29, 29, 29)
                .addGroup(jPDatosRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPDatosRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDatosRemitenteLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPDatosRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCalleCarrera)
                            .addComponent(jTCalleCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPDatosRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNoDeVivienda)
                            .addComponent(jTNoDeVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDatosRemitenteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(jPDatosRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPais, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCiudad)
                    .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPDatosRemitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTelefono)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        getContentPane().add(jPDatosRemitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 620, 320));

        TablaDatosDelRemitente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaDatosDelRemitente);

        javax.swing.GroupLayout jPTablaLayout = new javax.swing.GroupLayout(jPTabla);
        jPTabla.setLayout(jPTablaLayout);
        jPTablaLayout.setHorizontalGroup(
            jPTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        jPTablaLayout.setVerticalGroup(
            jPTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 600, 300));

        jBGuardar.setBackground(new java.awt.Color(153, 255, 255));
        jBGuardar.setFont(new java.awt.Font("Orbitron", 1, 18)); // NOI18N
        jBGuardar.setText("GUARDAR");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, 40));

        jBCancelar.setBackground(new java.awt.Color(102, 255, 255));
        jBCancelar.setFont(new java.awt.Font("Orbitron", 1, 18)); // NOI18N
        jBCancelar.setText("CANCELAR");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, -1, 40));

        jLTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLTitulo.setFont(new java.awt.Font("Orbitron", 1, 68)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo.setText("DELIVERY - UPAR");
        getContentPane().add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 800, 90));

        jBEliminar.setBackground(new java.awt.Color(102, 255, 255));
        jBEliminar.setFont(new java.awt.Font("Orbitron", 1, 18)); // NOI18N
        jBEliminar.setText("ELIMINAR");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, -1, 40));

        jLFormatoDePaqueteria.setBackground(new java.awt.Color(153, 255, 255));
        jLFormatoDePaqueteria.setFont(new java.awt.Font("Orbitron", 1, 36)); // NOI18N
        jLFormatoDePaqueteria.setForeground(new java.awt.Color(153, 255, 255));
        jLFormatoDePaqueteria.setText("Formato de paqueteria");
        getContentPane().add(jLFormatoDePaqueteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 560, -1));

        jBSiguiente.setBackground(new java.awt.Color(102, 255, 255));
        jBSiguiente.setFont(new java.awt.Font("Orbitron", 1, 18)); // NOI18N
        jBSiguiente.setText("Siguiente");
        jBSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jBSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 590, -1, 40));

        jLFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo456.jpg"))); // NOI18N
        getContentPane().add(jLFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1372, 708));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void ArchivarDatos() throws FileNotFoundException{
     FileOutputStream hp=new FileOutputStream("RegistroDeliveryUparRemitente.txt",true);
     DataOutputStream ph=new DataOutputStream(hp);
 
     try {
        String NombresCompletosR,CalleCarreraR,NodeViviendaR,Pais,Ciudad,TelefonoR;
//                NombresCompletosR,CalleCarreraR,NodeViviendaR,Pais,Ciudad,TelefonoR,
//                Tipo,Largo,Ancho,Alto,Pesokg,Descripcion,ValorDeclarado,
//                FechaLimite,Observaciones;
        

        NombresCompletosR=jTNombreCompleto.getText();
        CalleCarreraR=jTCalleCarrera.getText();
        NodeViviendaR=jTNoDeVivienda.getText();
        Pais=jTextFieldPais.getText();
        Ciudad=jTextFieldCiudad.getText();
        TelefonoR=jTextFieldTelefono.getText();
        

        ph.writeUTF(NombresCompletosR);
        ph.writeUTF(CalleCarreraR);
        ph.writeUTF(NodeViviendaR);
        ph.writeUTF(Pais);
        ph.writeUTF(Ciudad);
        ph.writeUTF(TelefonoR);

        } catch (Exception k) {
        }
}
    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed

        try{ ArchivarDatos();    
            } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaRegistroRemitente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        HMP.addRow(new Object[]{
            jTNombreCompleto.getText(), jTCalleCarrera.getText(),jTNoDeVivienda.getText(),jTextFieldPais.getText(),jTextFieldCiudad.getText(),jTextFieldTelefono.getText()
        });

        

        jTNombreCompleto.setText("");
        jTCalleCarrera.setText("");
        jTNoDeVivienda.setText("");
        jTextFieldPais.setText("");
        jTextFieldCiudad.setText("");
        jTextFieldTelefono.setText("");
      
        
                                           
        
        
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
       
        jTNombreCompleto.setText("");
        jTCalleCarrera.setText("");
        jTNoDeVivienda.setText("");
        jTextFieldPais.setText("");
        jTextFieldCiudad.setText("");
        jTextFieldTelefono.setText("");
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTCalleCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCalleCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCalleCarreraActionPerformed

    private void jTextFieldCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCiudadActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        int fila = TablaDatosDelRemitente.getSelectedRow ();
        if (fila>=0){
            HMP.removeRow(fila);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccionar FIla, Por favor ");
        }
    
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSiguienteActionPerformed
            
        VentanaRegistroPaquete H =new VentanaRegistroPaquete();
            H.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jBSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatosDelRemitente;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBSiguiente;
    private javax.swing.JLabel jLCalleCarrera;
    private javax.swing.JLabel jLCiudad;
    private javax.swing.JLabel jLDatosDelRemitente;
    private javax.swing.JLabel jLDireccion;
    private javax.swing.JLabel jLFondo1;
    private javax.swing.JLabel jLFormatoDePaqueteria;
    private javax.swing.JLabel jLNoDeVivienda;
    private javax.swing.JLabel jLNombreCompleto;
    private javax.swing.JLabel jLPais;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPDatosRemitente;
    private javax.swing.JPanel jPTabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCalleCarrera;
    private javax.swing.JTextField jTNoDeVivienda;
    private javax.swing.JTextField jTNombreCompleto;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
